### ISSUE TITLE
Reclaiming `pypush` package name on PyPI

### ISSUE THREAD

**Issue by JJTech0130** [viveksjain/pypush#5]
As you are no doubt aware, this package is using the name `pypush` on PyPI. This project has been abandoned for close to a decade, and does not appear to have any users or dependents.

I have created my own https://github.com/JJTech0130/pypush, for which unfortunately chose the same name. As I already have many people using it, it is a bit late to change the name, but I would now like to clean it up and publish on PyPI.

I was wondering if you would let me reclaim the package name? I've already reached out to you over email, but I wasn't sure if you received it so I am reaching out here as well.

I'd be really grateful if you'd be willing to do this, but could you please respond with your opinion either way so I know and can rename the project if necessary?

Thanks in advance,
JJTech

**Comment by viveksjain** [comment]
Hi, yes you are right that this project is not in active development. However, I do still use it occasionally. Unfortunately I don't think it's a good idea to have the same package name change to a completely different package, as it could cause confusion; and for anyone that still has it installed, it would create very unexpected behavior if they ever upgrade their pip packages.

**Comment by JJTech0130** [comment]
Hi again!

I don't want to nag you, but I would really appreciate it if you might reconsider your decision. At this point, my pypush project has grown much bigger, to the point where if I rename it now it would cause quite a lot of confusion (referenced by name in a couple of news articles: https://www.wired.com/story/beeper-android-iphone-texting-blue-bubbles/ for example)

At this point, your project has been unmaintained for over a decade, and it is still based on Python 2, which is now completely obsolete.

Looking at the download statistics, it looks like all recent installs have been from recent version of Python, which wouldn't be able to run it, meaning they are either background noise from mirrors and other ecosystem projects, or they are people actually trying to install something else who have the wrong package name.

As you probably know, it's much harder to get a good name on PyPI nowadays, with most short, memorable package names being already taken like this one.

Feel free to reach out to me directly at `jjtech@jjtech.dev`

Thanks again,
JJTech

**Comment by viveksjain** [comment]
Thanks for the additional context, awesome project! I remember reading about it in the news, didn't realize that was your project. I'd be happy to transfer it, let me know how to proceed. I'm still not sure how pip will behave if I try to upgrade the package after transfer, but there's probably very few people that still have it installed.

**Comment by JJTech0130** [comment]
Sorry for the late reply, somehow GitHub didn't notify me...
I'm https://pypi.org/user/jjtech/ on PyPI, I think if you just add me in the collaborators tab I should be able to upload releases.
If you want I can start numbering my releases at 2.0.0, just to make extra sure there aren't any weird issues with it pulling the old version or something.
Thanks so much for considering this, really appreciate it!

**Comment by ralebaskinson** [comment]
Invited you as owner, feel free to delete the older releases also. Regardless, starting at version 2.0 seems like a good idea.

**Comment by viveksjain** [comment]
Invited you as owner, feel free to delete the older releases also. Regardless, starting at version 2.0 seems like a good idea.

**Comment by JJTech0130** [comment]
Thanks so much!
